package grondag.adversity.superblock.model.painter.surface;

/**
 * Used by painters to know how to UV map a surface for painting.
 */
public enum SurfaceTopology
{
    /** 
     * Surface represents six faces of a single block.
     * Each quad in this surface will be tagged with a side
     * and will have raw UV values in the range 0 - 1.
     * 
     * UV scale will always be 1.0
     */
    CUBIC,
    
    /** 
     * Surface represents a continuous surface that is sliced into
     * quads that are each one block high and wide.
     * Quads tile in both dimensions and can extend for any distance.
     * 
     * A UV distance of 1 represents one block in world.
     * (UV scale on the surface instance will be 1.0)
     * UV values range from 0 through 256 and then repeat.
     * This means applied textures repeat every 256 blocks in both directions of the plane.
     *
     * Texture rotation and alternation is driven by relative position of UV coordinates
     * within the 256 x 256 block plane.
     */
    TILED,
 
    /**
     * Similar to TILED, except that tiles must wrap in one dimension.
     * "Wrap" means tiles must join with self without any seam.
     * 
     * Length of 1.0 in UV coordinates as generated by shape will be
     * square but will only be *approximately* one block-width in world.
     * Thus, textures applied by painter may appear slightly stretched or compressed in world.
     * 
     * Min U or V be 0 and max of same will be an integer.
     */
    CYLINDRICAL,
    
    /**
     * Texture wraps in both dimensions.  
     * 
     * Length of 1.0 in UV coordinates as generated by shape will be
     * square but will only be *approximately* one block-width in world.
     * Thus, textures applied by painter may appear slightly stretched or compressed in world.
     * 
     * Min UV will be 0,0 and Max UV will be integers.
     */
    TOROIDAL
    
}
