@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package grondag.hard_science.superblock.model.shape.machine;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;
import grondag.exotic_matter.varia.FieldsAreNonnullByDefault;